version: "3"
services:
    db:
        image: "monsieurbiz/mariadb:latest"
        volumes:
            - "database:/var/lib/mysql:rw,cached"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_DATABASE: "sylius_dev"
    mail:
        image: "monsieurbiz/mailcatcher"
        ports:
            - "1080:1080"
            - "1025:1025"
    node:
        build:
            context: node/
            args:
                USER_UID: ${USER_UID}
        volumes:
            - ../../:/var/www:rw,delegated
volumes:
    database: {}
